### ISSUE TITLE
깃 컨벤션 설정 및 템플릿 생성 

### ISSUE THREAD

**Issue by ej070961** [9oormthonUniv-seoultech/PROJECT_TEAM_WEB_FE2#1]
## ✅ Description
프로젝트 깃 컨벤션을 설정하고 템플릿을 생성합니다. 

## ✔️ TODO
- [ ] label 설정 및 생성
- [ ] PR template 설정 및 생성
- [ ] 리드미에 깃 컨벤션 등록
