### ISSUE TITLE
포토부스 커스텀 마커 생성 및 현위치 마커 구현

### ISSUE THREAD

**Issue by ej070961** [9oormthonUniv-seoultech/PROJECT_TEAM_WEB_FE2#16]
## ✅ Description
- 확정된 포토부스 카테고리에 따라 홈화면에 띄울 커스텀 마커를 구현하고, 현위치를 띄우는 마커를 구현
## ✔️ TODO
- [x] 포토부스 카테고리 데이터 정의
- [x] 커스텀 마커 컴포넌트 생성 
- [x] 현위치 마커 구현
