### ISSUE TITLE
카카오 로그인 및 유저정보 상태관리 기능 구현 

### ISSUE THREAD

**Issue by ej070961** [9oormthonUniv-seoultech/PROJECT_TEAM_WEB_FE2#7]
## ✅ Description
로그인 화면과 카카오 로그인 기능을 구현하고, 로그인정보 전역 상태관리 설정

## ✔️ TODO
- [x] 로그인 화면  UI 구현
- [x] 카카오로그인 API 연결
- [x] 로그인 전역 상태관리
